In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[1]

1

In [6]:
arr[1: 5]

array([1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
#shallow copy
slice_of_arr = arr[:6]

In [14]:
slice_of_arr[:] = 300

In [15]:
arr

array([300, 300, 300, 300, 300, 300,   6,   7,   8,   9])

In [16]:
# deep copy
arr_copy = arr.copy()

In [18]:
arr_copy[:] = 90

In [19]:
arr_copy

array([90, 90, 90, 90, 90, 90, 90, 90, 90, 90])

In [20]:
arr

array([300, 300, 300, 300, 300, 300,   6,   7,   8,   9])

In [21]:
 arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr = np.array([2, 4, 55,2, 5, 2,6, 5, 3])

In [33]:
# conditional selection
less_than_3 = arr[arr <= 3]

In [34]:
less_than_3

array([2, 2, 2, 3])

In [40]:
# way to make 2d array
arr_2d = np.arange(50).reshape(5, 10)

In [41]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])